DROP TABLE IF EXISTS sys_user;

CREATE TABLE sys_user(
    id BIGINT NOT NULL ,
    name VARCHAR(30) NULL DEFAULT NULL,
    age INT NULL DEFAULT NULL,
    email VARCHAR(50) NULL DEFAULT NULL,
    PRIMARY KEY(id)
)
